import NavBar from '@/components/navigation/NavBar'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import "./index.scss"
//old providers
import { UserProvider } from '@/contexts/user.context'
import { CartProvider } from '@/contexts/cart.context'
//new providers
//import ReduxProvider from '@/providers/ReduxProvider'
import ReduxProviderSaga from '@/providers/ReduxProviderSaga'
//import ReduxProviderThunk from '@/providers/ReduxProviderThunk'
//import ReduxProviderToolkit from '@/providers/ReduxProviderToolkit'
import { StripeProvider } from '@/contexts/stripe.context'


const sans = Open_Sans({ subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//change the first value based on what provider you want
//of course you will need to change other values in each component separately
//default is "saga" since I think is the best one
export const providerType = 'saga' as 'saga' | 'thunk' | 'toolkit' | 'redux';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  //user and cart providers are from react context
  return (
    <html lang="en">
      <body className={sans.className}>
        <ReduxProviderSaga>
          <StripeProvider>
            {/* <UserProvider> */}
            {/* <CartProvider> */}
            <NavBar />
            {children}
            {/* </CartProvider> */}
            {/* </UserProvider> */}
          </StripeProvider>
        </ReduxProviderSaga>
      </body>
    </html>
  )
}


